language: node_js
sudo: required
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
  - polylint
env:
  global:
    - secure: j5KsAgPahcMv1sLdtzohv1FAMmsT6rjBgSpvnewgXUAtdyBdJXEHVR2r8ivmVGx5DGLrUbSaD76WOHZ/+YxUMxjrrY+fNZqwUIhDEI5GL8vnJ4PafLmzWerta7xrLVv85D0FB/aKQPeWdAIybBuZN2ofO2FJ5zNlPP7TLHpIJmw=
    - secure: XiWJngoy+exvakYD4TVwtvTKcgsbcI7meoAOc4h2gesfpA6ZeC0GhhSYAAb3buDhPngSHrqTc80j7aFS6ZvUkD5CdPtb1moEo2d5SbJeE4zu3XxWO2Daf3y032hoJzXtV73x545poBj50OD9Py1lfrwYE7tokYcb0hlMg7YQNjs=
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - 'true || xvfb-run wct'
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then true || wct -s 'default'; fi"
dist: trusty
